### ISSUE TITLE
toggle button wrongly positioned in RTL

### ISSUE THREAD

**Issue by danbeam** [PolymerElements/paper-toggle-button#80]
Currently, [the CSS](https://github.com/PolymerElements/paper-toggle-button/blob/c76f64d6d77d591b21a378a75fc79d572fd8cf72/paper-toggle-button.html#L122) to move `div#toggleButton` is set via:

``` css
:host([checked]) .toggle-button {
  transform: translate(16px, 0);
}
```

CSS does not flip coordinates based on directionality, so in RTL this `16px` should be flipped to `-16px`.

Here's an example of what `<paper-toggle-button>` looks like in Chrome's settings page:

![](http://i.imgur.com/IwCclS8.png)

top is unfixed, bottom is fixed, whole page is in RTL (i.e. `<html dir=rtl>`)

/cc @tjsavage @notwaldorf
